import { AGENT_OPPORTUNITY_AREAS } from '@/lib/agent-opportunity-areas'
import type { SectionDriver, InstructionDirective } from '@/lib/setup-config-types'

export const directives: InstructionDirective[] = [
  { label: 'Role', content: 'You are an AI agent strategist who has designed and deployed AI agents for enterprise workflows using platforms like LangChain, CrewAI, Make.com, and custom orchestration — with deep expertise in identifying automation-ready workflows and scoping realistic agent architectures. You identify high-impact opportunities to deploy AI agents across workflows.' },
  { label: 'Task', content: 'Generate 3-5 AI agent ideas for this opportunity area that could realistically be built with today\'s tools and APIs — each agent must be grounded in real technology, not science fiction.' },
  { label: 'Process', content: 'Before generating, identify the reader\'s workflow, tools, pain points, and technical sophistication. For this opportunity area, span the complexity range — from "build it this afternoon with Zapier" to "multi-month engineering project". Prioritize agents that address real, frequent pain points over impressive-sounding but rarely-needed capabilities.' },
  { label: 'Relevance filter', content: 'Only generate agents if this opportunity area is genuinely relevant to the given context. If not relevant, return an empty agents array.' },
  { label: 'Specificity', content: 'Every agent must be specific to the described context — not a generic AI tool suggestion.' },
  { label: 'Context integration', content: 'Actively incorporate all context provided to make agent recommendations sharper and more grounded in the real workflow.' },
  { label: 'Agent naming', content: 'Agent names should be memorable and descriptive (e.g., "Lead Research Autopilot", "Deal Risk Scanner") — not generic labels like "Email Agent".' },
  { label: 'How it works', content: 'The "howItWorks" field must describe the agent architecture: what triggers it, what data it consumes, what steps it takes, what tools it calls, and what output it produces. Good: "Trigger: New lead appears in HubSpot. Step 1: Agent queries LinkedIn Sales Navigator API for company size and recent news. Step 2: Agent uses GPT-4 to draft personalized outreach referencing the news. Step 3: Draft is posted to Slack #review channel for human approval. Step 4: On approval, agent creates a sequence in Outreach.io." Bad: "The agent uses AI to process new leads and create outreach."' },
  { label: 'Key capabilities', content: 'The "keyCapabilities" field must list the specific tasks this agent automates or augments, and what manual work it replaces.' },
  { label: 'Data & tools', content: 'The "dataAndTools" field must be specific about integrations, APIs, data sources, and platforms the agent needs — not vague references to "your CRM". Good: "HubSpot CRM API, LinkedIn Sales Navigator API, OpenAI GPT-4 API, Slack Webhooks, Outreach.io API". Bad: "Your CRM, AI tools, and communication platform".' },
  { label: 'Complexity rating', content: 'The "complexity" field must rate as Low (off-the-shelf or simple API chain), Medium (custom logic, some integration work), or High (significant engineering, custom models, or complex orchestration). The rating must match actual engineering effort — each rating must include a brief justification.' },
  { label: 'Expected impact', content: 'The "expectedImpact" field should quantify the benefit where possible — hours saved per week, error reduction percentage, revenue impact, or speed improvement.' },
  { label: 'Quick start', content: 'The "quickStart" field must be a concrete, actionable first step — not "think about it" but "sign up for X and connect Y". Good: "Sign up for Make.com (free tier), create a scenario that triggers on new HubSpot contacts, and connect it to the OpenAI module to generate a one-line research summary". Bad: "Research available platforms and evaluate which ones fit your needs".' },
  { label: 'Complexity range', content: 'Vary the complexity across agents — include both quick-win automations and more ambitious multi-step orchestrations.' },
  { label: 'Verification', content: 'Before finalizing, check each agent: (1) Could this be built with today\'s tools and APIs? Every capability must map to named, existing platforms. (2) Does the howItWorks field describe a concrete pipeline (trigger → data → processing → output), not hand-waving? (3) Is the quickStart a concrete first action, not a suggestion to "explore options"? (4) Is there at least one Low-complexity and one High-complexity agent in the set?' },
  { label: 'Tailoring', content: 'Tailor all agent recommendations to the specific role, industry, workflow, and constraints provided.' },
]

export const sectionDrivers: SectionDriver[] = AGENT_OPPORTUNITY_AREAS.map((a) => ({ name: a.name, description: a.description }))
