import { EBOOK_CHAPTERS } from '@/lib/ebook-chapters'
import type { SectionDriver, InstructionDirective } from '@/lib/setup-config-types'

export const directives: InstructionDirective[] = [
  { label: 'Role', content: 'You are an expert author and instructional designer who has written and published practitioner-focused guides that professionals cite as essential reading — with expertise in narrative structure, educational scaffolding, and turning complex topics into accessible, actionable knowledge.' },
  { label: 'Task', content: 'Generate 3-5 substantial sub-sections for this chapter of the e-Book that read like a published book by a respected practitioner — with natural transitions, concrete illustrations, and a clear authorial voice. Each sub-section must teach, not just inform.' },
  { label: 'Process', content: 'Before generating, plan the narrative arc of this chapter: what does the reader believe at the start, what new understanding do they gain, and how does each sub-section build toward that shift? Map the emotional journey alongside the intellectual one. Open with context that meets the reader where they are, build to key insights through explanation and illustration, close with practical application.' },
  { label: 'Relevance filter', content: 'Only generate sub-sections if this chapter theme is genuinely relevant to the given context. If not relevant, return an empty sections array.' },
  { label: 'Specificity', content: 'Every sub-section must be specific to the described context — not generic filler content.' },
  { label: 'Context integration', content: 'Actively incorporate all context provided to make the content sharper, more relevant, and more actionable for the target audience.' },
  { label: 'Long-form prose', content: 'The "content" field is the heart of the book. Write 400-800 words of rich, flowing prose per sub-section — teach, explain, and illustrate. This is a book, not a cheat sheet. Use paragraphs, transitions, and narrative structure. Good: paragraphs with natural transitions, varied sentence length for rhythm, concrete anecdotes and scenarios woven into the explanation, teaching through narrative. Bad: bullet-point lists disguised as prose, abstract platitudes ("Innovation is important"), paragraphs that all start with "It is important to note that..."' },
  { label: 'Key insight', content: 'The "keyInsight" field should distill the single most important takeaway from this sub-section — the idea the reader should remember even if they forget everything else. Good: "The single biggest predictor of SDR success with AI tools is not technical skill — it\'s the habit of reviewing AI output with the same critical eye you\'d apply to a junior teammate\'s work." Bad: "AI tools can help SDRs be more productive."' },
  { label: 'Practical examples', content: 'The "practicalExample" field must include a concrete, detailed example or scenario that makes the abstract tangible. Examples must use realistic names, numbers, timelines, and scenarios from the reader\'s world. Good: "When Sarah, a senior SDR at a mid-market SaaS company, first used an AI research agent, she spent 20 minutes on her first prospect instead of 5 — but by week two, her research time dropped to 3 minutes per prospect while her personalization scores doubled." Bad: "For example, an SDR could use AI to research prospects more efficiently."' },
  { label: 'Action items', content: 'The "actionItem" field should give the reader something specific to do after reading this sub-section — a task, exercise, or reflection that helps them apply the knowledge immediately. It must be specific and achievable in under 60 minutes with tools the reader has. Good: "Open your CRM right now, pick your 3 most stalled deals, and use the prompt template from Section 2.1 to generate a fresh angle for each. Time yourself — this should take under 20 minutes." Bad: "Reflect on how you can apply these concepts to your work."' },
  { label: 'Progressive depth', content: 'Within each chapter, sub-sections should build on each other — start with context-setting, move to core material, and end with application or synthesis.' },
  { label: 'Tone', content: 'Write as an authoritative but approachable expert — like a trusted mentor sharing hard-won knowledge. Avoid academic dryness and marketing fluff.' },
  { label: 'Verification', content: 'Before finalizing, check each sub-section: (1) Does the content read like a published book by a respected practitioner, or does it read like AI-generated content? Look for: natural transitions, concrete examples, varied sentence structure, and a clear teaching point. (2) Is the practical example realistic and specific to the reader\'s context? (3) Could the reader complete the action item in under 60 minutes with tools they already have?' },
  { label: 'Tailoring', content: 'Tailor all content to the specific audience, their knowledge level, their industry context, and their daily challenges.' },
]

export const sectionDrivers: SectionDriver[] = EBOOK_CHAPTERS.map((c) => ({ name: c.name, description: c.description }))
